# Generated by Django 4.2.5 on 2023-10-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='imagen_default.png', upload_to='peliculas', verbose_name='Imgen'),
        ),
    ]
